name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -project GithubActionsTestApp.xcodeproj -scheme GithubActionsTestApp -destination "platform=iOS Simulator,name=iPhone 12,OS=14.4"
#    - name: Run tests
#      run: swift test -v
